--LISTAR TODAS LOS REGISTROS POR SUCURSAL

ALTER PROCEDURE SP_L_CATEGORIA_01
@SUC_ID INT
AS
BEGIN 
	SELECT * FROM [dbo].[TM_CATEGORIA]
	WHERE
	SUC_ID=@SUC_ID
	AND EST=1
END

-- MODIFICAR SP
--SP_HELPTEXT SP_LCATEGORIA_01
 
-- EJECUTAR SP
--EXEC SP_L_CATEGORIA_01 


-- OBTENER REGISTRO POR ID
CREATE PROCEDURE SP_L_CATEGORIA_02
@CAT_ID INT
AS
BEGIN 
	SELECT * FROM [dbo].[TM_CATEGORIA]
	WHERE
	CAT_ID = @CAT_ID
END


-- ELIMINAR REGISTRO 
CREATE PROCEDURE SP_D_CATEGORIA_01
@CAT_ID INT
AS
BEGIN 
	UPDATE [dbo].[TM_CATEGORIA]
	SET
		EST = 0
	WHERE
		CAT_ID = @CAT_ID
END


-- INSERTAR REGISTRO
CREATE PROCEDURE SP_I_CATEGORIA_01
@SUC_ID INT,
@CAT_NOM VARCHAR(150)
AS
BEGIN 
	INSERT INTO [dbo].[TM_CATEGORIA]
	(SUC_ID,CAT_NOM,FECH_CREA,EST)
	VALUES
	(@SUC_ID,@CAT_NOM,GETDATE(),1)
END


-- ACTUALIZAR NUEVO REGISTRO
CREATE PROCEDURE SP_U_CATEGORIA_01
@CAT_ID INT,
@SUC_ID INT,
@CAT_NOM VARCHAR(150)
AS
BEGIN 
	UPDATE TM_CATEGORIA
	SET
		SUC_ID = @SUC_ID,
		CAT_NOM = @CAT_NOM
	WHERE
		CAT_ID = @CAT_ID
END